### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: master-atul/tar-action@v1.1.0,

### ISSUE THREAD

**Issue by neilyoung** [a7ul/tar-action#22]
Any solution in sight?

**Comment by a7ul** [comment]
Could you raise a pr please?

**Comment by neilyoung** [comment]
Well, I would, but I'm not familiar with GH plugins. I don't even know, where this message is originated. I'm just trying to update my CI script and trying to get rid of all plugins, showing up this warning. That worked for three outdated and abandoned plugins so far, just not for yours (in fact I didn't find a replacement).

Don't get me wrong: The plugin works. It is just likely, that starting from Summer this year it will no longer work.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/#:~:text=Node%2012%20has%20been%20out,on%20Node16%20by%20Summer%202023.

**Comment by neilyoung** [comment]
What I can see so far wouldn't let me believe you would have a problem with Node 12

https://github.com/a7ul/tar-action/blob/master/action.yml

Note: node16

What else do they want?

**Comment by neilyoung** [comment]
I think you will also have to remove the "set-output", since this is also deprecated...

**Comment by neilyoung** [comment]
Maybe you have inherited the two warnings from some dependencies. Please check if the pending PRs help

**Comment by neilyoung** [comment]
OK, I replaced your plugin with a manual tar command and all warnings are gone. Sufficient for me. Please comment here, once you have fixed it
