### ISSUE TITLE
Support for node20

### ISSUE THREAD

**Issue by mharting** [a7ul/tar-action#26]
Google is deprecating node16 for GH actions:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20
```

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by johanvilela** [comment]
There is already a [pull request](https://github.com/a7ul/tar-action/pull/27) about this topic, but it is from March 3
